//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18063 版自动生成。
// 
#pragma warning disable 1591

namespace Web服务测试.QCHATQ2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/wsdl/soap/”中的可选 WSDL 扩展元素“body”。
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QchatQEDSoapBinding", Namespace="http://qed.qchat.telecom.cn")]
    public partial class QchatQEDService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private @string usernameField;
        
        private string1 passwordField;
        
        private string2 deviceIDField;
        
        private string3 sequenceField;
        
        private System.Threading.SendOrPostCallback queryCompanyOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryCompanyGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryCompanyUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback addGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryGroupMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback addGroupMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateGroupMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteGroupMemberOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryUserGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateUserStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QchatQEDService() {
            this.Url = global::Web服务测试.Properties.Settings.Default.Web服务测试_QCHATQ2_QchatQEDService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public @string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        public string1 Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        public string2 DeviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
            }
        }
        
        public string3 Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event queryCompanyCompletedEventHandler queryCompanyCompleted;
        
        /// <remarks/>
        public event queryCompanyGroupCompletedEventHandler queryCompanyGroupCompleted;
        
        /// <remarks/>
        public event queryCompanyUserCompletedEventHandler queryCompanyUserCompleted;
        
        /// <remarks/>
        public event queryGroupCompletedEventHandler queryGroupCompleted;
        
        /// <remarks/>
        public event addGroupCompletedEventHandler addGroupCompleted;
        
        /// <remarks/>
        public event deleteGroupCompletedEventHandler deleteGroupCompleted;
        
        /// <remarks/>
        public event updateGroupCompletedEventHandler updateGroupCompleted;
        
        /// <remarks/>
        public event queryGroupMemberCompletedEventHandler queryGroupMemberCompleted;
        
        /// <remarks/>
        public event addGroupMemberCompletedEventHandler addGroupMemberCompleted;
        
        /// <remarks/>
        public event updateGroupMemberCompletedEventHandler updateGroupMemberCompleted;
        
        /// <remarks/>
        public event deleteGroupMemberCompletedEventHandler deleteGroupMemberCompleted;
        
        /// <remarks/>
        public event queryUserCompletedEventHandler queryUserCompleted;
        
        /// <remarks/>
        public event queryUserGroupCompletedEventHandler queryUserGroupCompleted;
        
        /// <remarks/>
        public event updateUserCompletedEventHandler updateUserCompleted;
        
        /// <remarks/>
        public event updateUserStatusCompletedEventHandler updateUserStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse queryCompany(QedRequest request) {
            object[] results = this.Invoke("queryCompany", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryCompanyAsync(QedRequest request) {
            this.queryCompanyAsync(request, null);
        }
        
        /// <remarks/>
        public void queryCompanyAsync(QedRequest request, object userState) {
            if ((this.queryCompanyOperationCompleted == null)) {
                this.queryCompanyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryCompanyOperationCompleted);
            }
            this.InvokeAsync("queryCompany", new object[] {
                        request}, this.queryCompanyOperationCompleted, userState);
        }
        
        private void OnqueryCompanyOperationCompleted(object arg) {
            if ((this.queryCompanyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCompanyCompleted(this, new queryCompanyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse queryCompanyGroup(QedRequest request) {
            object[] results = this.Invoke("queryCompanyGroup", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryCompanyGroupAsync(QedRequest request) {
            this.queryCompanyGroupAsync(request, null);
        }
        
        /// <remarks/>
        public void queryCompanyGroupAsync(QedRequest request, object userState) {
            if ((this.queryCompanyGroupOperationCompleted == null)) {
                this.queryCompanyGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryCompanyGroupOperationCompleted);
            }
            this.InvokeAsync("queryCompanyGroup", new object[] {
                        request}, this.queryCompanyGroupOperationCompleted, userState);
        }
        
        private void OnqueryCompanyGroupOperationCompleted(object arg) {
            if ((this.queryCompanyGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCompanyGroupCompleted(this, new queryCompanyGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse queryCompanyUser(QedRequest request) {
            object[] results = this.Invoke("queryCompanyUser", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryCompanyUserAsync(QedRequest request) {
            this.queryCompanyUserAsync(request, null);
        }
        
        /// <remarks/>
        public void queryCompanyUserAsync(QedRequest request, object userState) {
            if ((this.queryCompanyUserOperationCompleted == null)) {
                this.queryCompanyUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryCompanyUserOperationCompleted);
            }
            this.InvokeAsync("queryCompanyUser", new object[] {
                        request}, this.queryCompanyUserOperationCompleted, userState);
        }
        
        private void OnqueryCompanyUserOperationCompleted(object arg) {
            if ((this.queryCompanyUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCompanyUserCompleted(this, new queryCompanyUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse queryGroup(QedRequest request) {
            object[] results = this.Invoke("queryGroup", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryGroupAsync(QedRequest request) {
            this.queryGroupAsync(request, null);
        }
        
        /// <remarks/>
        public void queryGroupAsync(QedRequest request, object userState) {
            if ((this.queryGroupOperationCompleted == null)) {
                this.queryGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryGroupOperationCompleted);
            }
            this.InvokeAsync("queryGroup", new object[] {
                        request}, this.queryGroupOperationCompleted, userState);
        }
        
        private void OnqueryGroupOperationCompleted(object arg) {
            if ((this.queryGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryGroupCompleted(this, new queryGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse addGroup(QedRequest request) {
            object[] results = this.Invoke("addGroup", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void addGroupAsync(QedRequest request) {
            this.addGroupAsync(request, null);
        }
        
        /// <remarks/>
        public void addGroupAsync(QedRequest request, object userState) {
            if ((this.addGroupOperationCompleted == null)) {
                this.addGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddGroupOperationCompleted);
            }
            this.InvokeAsync("addGroup", new object[] {
                        request}, this.addGroupOperationCompleted, userState);
        }
        
        private void OnaddGroupOperationCompleted(object arg) {
            if ((this.addGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addGroupCompleted(this, new addGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse deleteGroup(QedRequest request) {
            object[] results = this.Invoke("deleteGroup", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteGroupAsync(QedRequest request) {
            this.deleteGroupAsync(request, null);
        }
        
        /// <remarks/>
        public void deleteGroupAsync(QedRequest request, object userState) {
            if ((this.deleteGroupOperationCompleted == null)) {
                this.deleteGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteGroupOperationCompleted);
            }
            this.InvokeAsync("deleteGroup", new object[] {
                        request}, this.deleteGroupOperationCompleted, userState);
        }
        
        private void OndeleteGroupOperationCompleted(object arg) {
            if ((this.deleteGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteGroupCompleted(this, new deleteGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse updateGroup(QedRequest request) {
            object[] results = this.Invoke("updateGroup", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateGroupAsync(QedRequest request) {
            this.updateGroupAsync(request, null);
        }
        
        /// <remarks/>
        public void updateGroupAsync(QedRequest request, object userState) {
            if ((this.updateGroupOperationCompleted == null)) {
                this.updateGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateGroupOperationCompleted);
            }
            this.InvokeAsync("updateGroup", new object[] {
                        request}, this.updateGroupOperationCompleted, userState);
        }
        
        private void OnupdateGroupOperationCompleted(object arg) {
            if ((this.updateGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateGroupCompleted(this, new updateGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse queryGroupMember(QedRequest request) {
            object[] results = this.Invoke("queryGroupMember", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryGroupMemberAsync(QedRequest request) {
            this.queryGroupMemberAsync(request, null);
        }
        
        /// <remarks/>
        public void queryGroupMemberAsync(QedRequest request, object userState) {
            if ((this.queryGroupMemberOperationCompleted == null)) {
                this.queryGroupMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryGroupMemberOperationCompleted);
            }
            this.InvokeAsync("queryGroupMember", new object[] {
                        request}, this.queryGroupMemberOperationCompleted, userState);
        }
        
        private void OnqueryGroupMemberOperationCompleted(object arg) {
            if ((this.queryGroupMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryGroupMemberCompleted(this, new queryGroupMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse addGroupMember(QedRequest request) {
            object[] results = this.Invoke("addGroupMember", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void addGroupMemberAsync(QedRequest request) {
            this.addGroupMemberAsync(request, null);
        }
        
        /// <remarks/>
        public void addGroupMemberAsync(QedRequest request, object userState) {
            if ((this.addGroupMemberOperationCompleted == null)) {
                this.addGroupMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddGroupMemberOperationCompleted);
            }
            this.InvokeAsync("addGroupMember", new object[] {
                        request}, this.addGroupMemberOperationCompleted, userState);
        }
        
        private void OnaddGroupMemberOperationCompleted(object arg) {
            if ((this.addGroupMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addGroupMemberCompleted(this, new addGroupMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse updateGroupMember(QedRequest request) {
            object[] results = this.Invoke("updateGroupMember", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateGroupMemberAsync(QedRequest request) {
            this.updateGroupMemberAsync(request, null);
        }
        
        /// <remarks/>
        public void updateGroupMemberAsync(QedRequest request, object userState) {
            if ((this.updateGroupMemberOperationCompleted == null)) {
                this.updateGroupMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateGroupMemberOperationCompleted);
            }
            this.InvokeAsync("updateGroupMember", new object[] {
                        request}, this.updateGroupMemberOperationCompleted, userState);
        }
        
        private void OnupdateGroupMemberOperationCompleted(object arg) {
            if ((this.updateGroupMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateGroupMemberCompleted(this, new updateGroupMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse deleteGroupMember(QedRequest request) {
            object[] results = this.Invoke("deleteGroupMember", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteGroupMemberAsync(QedRequest request) {
            this.deleteGroupMemberAsync(request, null);
        }
        
        /// <remarks/>
        public void deleteGroupMemberAsync(QedRequest request, object userState) {
            if ((this.deleteGroupMemberOperationCompleted == null)) {
                this.deleteGroupMemberOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteGroupMemberOperationCompleted);
            }
            this.InvokeAsync("deleteGroupMember", new object[] {
                        request}, this.deleteGroupMemberOperationCompleted, userState);
        }
        
        private void OndeleteGroupMemberOperationCompleted(object arg) {
            if ((this.deleteGroupMemberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteGroupMemberCompleted(this, new deleteGroupMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse queryUser(QedRequest request) {
            object[] results = this.Invoke("queryUser", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryUserAsync(QedRequest request) {
            this.queryUserAsync(request, null);
        }
        
        /// <remarks/>
        public void queryUserAsync(QedRequest request, object userState) {
            if ((this.queryUserOperationCompleted == null)) {
                this.queryUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryUserOperationCompleted);
            }
            this.InvokeAsync("queryUser", new object[] {
                        request}, this.queryUserOperationCompleted, userState);
        }
        
        private void OnqueryUserOperationCompleted(object arg) {
            if ((this.queryUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryUserCompleted(this, new queryUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse queryUserGroup(QedRequest request) {
            object[] results = this.Invoke("queryUserGroup", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryUserGroupAsync(QedRequest request) {
            this.queryUserGroupAsync(request, null);
        }
        
        /// <remarks/>
        public void queryUserGroupAsync(QedRequest request, object userState) {
            if ((this.queryUserGroupOperationCompleted == null)) {
                this.queryUserGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryUserGroupOperationCompleted);
            }
            this.InvokeAsync("queryUserGroup", new object[] {
                        request}, this.queryUserGroupOperationCompleted, userState);
        }
        
        private void OnqueryUserGroupOperationCompleted(object arg) {
            if ((this.queryUserGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryUserGroupCompleted(this, new queryUserGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse updateUser(QedRequest request) {
            object[] results = this.Invoke("updateUser", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateUserAsync(QedRequest request) {
            this.updateUserAsync(request, null);
        }
        
        /// <remarks/>
        public void updateUserAsync(QedRequest request, object userState) {
            if ((this.updateUserOperationCompleted == null)) {
                this.updateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateUserOperationCompleted);
            }
            this.InvokeAsync("updateUser", new object[] {
                        request}, this.updateUserOperationCompleted, userState);
        }
        
        private void OnupdateUserOperationCompleted(object arg) {
            if ((this.updateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateUserCompleted(this, new updateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("Sequence")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Username")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Password")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("DeviceID")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://qed.qchat.telecom.cn", ResponseNamespace="http://qed.qchat.telecom.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("qedResponse")]
        public QedResponse updateUserStatus(QedRequest request) {
            object[] results = this.Invoke("updateUserStatus", new object[] {
                        request});
            return ((QedResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateUserStatusAsync(QedRequest request) {
            this.updateUserStatusAsync(request, null);
        }
        
        /// <remarks/>
        public void updateUserStatusAsync(QedRequest request, object userState) {
            if ((this.updateUserStatusOperationCompleted == null)) {
                this.updateUserStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateUserStatusOperationCompleted);
            }
            this.InvokeAsync("updateUserStatus", new object[] {
                        request}, this.updateUserStatusOperationCompleted, userState);
        }
        
        private void OnupdateUserStatusOperationCompleted(object arg) {
            if ((this.updateUserStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateUserStatusCompleted(this, new updateUserStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(TypeName="string", Namespace="http://www.w3.org/2001/XMLSchema")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="string", Namespace="http://www.w3.org/2001/XMLSchema3")]
    [System.Xml.Serialization.XmlRootAttribute("Sequence", Namespace="http://qed.qchat.telecom.cn", IsNullable=false)]
    public partial class string3 : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2001/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("Username", Namespace="http://qed.qchat.telecom.cn", IsNullable=false)]
    public partial class @string : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(TypeName="string", Namespace="http://www.w3.org/2001/XMLSchema")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "string", Namespace = "http://www.w3.org/2001/XMLSchema1")]
    [System.Xml.Serialization.XmlRootAttribute("Password", Namespace="http://qed.qchat.telecom.cn", IsNullable=false)]
    public partial class string1 : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="string", Namespace="http://www.w3.org/2001/XMLSchema2")]
    [System.Xml.Serialization.XmlRootAttribute("DeviceID", Namespace="http://qed.qchat.telecom.cn", IsNullable=false)]
    public partial class string2 : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class QedRequest {
        
        private GroupMemberRequest groupMemRequestField;
        
        private AddGroupRequest addGroupRequestField;
        
        private GroupRequest groupRequestField;
        
        private QueryRequest queryRequestField;
        
        private UserRequest userRequestField;
        
        /// <remarks/>
        public GroupMemberRequest groupMemRequest {
            get {
                return this.groupMemRequestField;
            }
            set {
                this.groupMemRequestField = value;
            }
        }
        
        /// <remarks/>
        public AddGroupRequest addGroupRequest {
            get {
                return this.addGroupRequestField;
            }
            set {
                this.addGroupRequestField = value;
            }
        }
        
        /// <remarks/>
        public GroupRequest groupRequest {
            get {
                return this.groupRequestField;
            }
            set {
                this.groupRequestField = value;
            }
        }
        
        /// <remarks/>
        public QueryRequest queryRequest {
            get {
                return this.queryRequestField;
            }
            set {
                this.queryRequestField = value;
            }
        }
        
        /// <remarks/>
        public UserRequest userRequest {
            get {
                return this.userRequestField;
            }
            set {
                this.userRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class GroupMemberRequest {
        
        private int memberSizeField;
        
        private string groupCodeField;
        
        private GroupMemberInfo[] gMemInfoField;
        
        /// <remarks/>
        public int memberSize {
            get {
                return this.memberSizeField;
            }
            set {
                this.memberSizeField = value;
            }
        }
        
        /// <remarks/>
        public string groupCode {
            get {
                return this.groupCodeField;
            }
            set {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gMemInfo")]
        public GroupMemberInfo[] gMemInfo {
            get {
                return this.gMemInfoField;
            }
            set {
                this.gMemInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class GroupMemberInfo {
        
        private int levelField;
        
        private string nameField;
        
        private string numberField;
        
        private int typeField;
        
        /// <remarks/>
        public int level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class UserResponse {
        
        private Response responseField;
        
        private UserInfo userInfoField;
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public UserInfo userInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class Response {
        
        private string descriptionField;
        
        private string reserveField;
        
        private string returnCodeField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
            }
        }
        
        /// <remarks/>
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class UserInfo {
        
        private string callRestrictionField;
        
        private string imsiField;
        
        private string levelField;
        
        private string nameField;
        
        private string numberField;
        
        private string statusField;
        
        private string domainField;
        
        private string passwordField;
        
        /// <remarks/>
        public string callRestriction {
            get {
                return this.callRestrictionField;
            }
            set {
                this.callRestrictionField = value;
            }
        }
        
        /// <remarks/>
        public string imsi {
            get {
                return this.imsiField;
            }
            set {
                this.imsiField = value;
            }
        }
        
        /// <remarks/>
        public string level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class GroupUpdateResponse {
        
        private Response responseField;
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class DeleteGroupResponse {
        
        private Response responseField;
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class AddGroupResponse {
        
        private Response responseField;
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class GroupResponse {
        
        private GroupInfo groupInfoField;
        
        private Response responseField;
        
        /// <remarks/>
        public GroupInfo groupInfo {
            get {
                return this.groupInfoField;
            }
            set {
                this.groupInfoField = value;
            }
        }
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class GroupInfo {
        
        private string codeField;
        
        private string domainField;
        
        private int memberCountField;
        
        private string nameField;
        
        private string policyField;
        
        private string titleField;
        
        private int typeField;
        
        private int codecField;
        
        private bool codecFieldSpecified;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        public int memberCount {
            get {
                return this.memberCountField;
            }
            set {
                this.memberCountField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int codec {
            get {
                return this.codecField;
            }
            set {
                this.codecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codecSpecified {
            get {
                return this.codecFieldSpecified;
            }
            set {
                this.codecFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class GroupMemberResponse {
        
        private int countField;
        
        private Response[] responseField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("response")]
        public Response[] response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class CompanyInfo {
        
        private int adminCountField;
        
        private string companyNameField;
        
        private int groupCountField;
        
        private int userCountField;
        
        /// <remarks/>
        public int adminCount {
            get {
                return this.adminCountField;
            }
            set {
                this.adminCountField = value;
            }
        }
        
        /// <remarks/>
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public int groupCount {
            get {
                return this.groupCountField;
            }
            set {
                this.groupCountField = value;
            }
        }
        
        /// <remarks/>
        public int userCount {
            get {
                return this.userCountField;
            }
            set {
                this.userCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class CompanyResponse {
        
        private Response responseField;
        
        private CompanyInfo companyInfoField;
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public CompanyInfo companyInfo {
            get {
                return this.companyInfoField;
            }
            set {
                this.companyInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class CompanyUserResponse {
        
        private int countField;
        
        private Response responseField;
        
        private UserInfo[] userInfoField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userInfo")]
        public UserInfo[] userInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class CompanyGroupResponse {
        
        private GroupInfo[] groupInfoField;
        
        private int countField;
        
        private Response responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("groupInfo")]
        public GroupInfo[] groupInfo {
            get {
                return this.groupInfoField;
            }
            set {
                this.groupInfoField = value;
            }
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class UserGroupInfo {
        
        private string companyIDField;
        
        private string groupCodeField;
        
        private string groupNameField;
        
        private int groupTypeField;
        
        private int levelField;
        
        private string memberAliasNameField;
        
        private int memberTypeField;
        
        private int policyField;
        
        private string titleField;
        
        /// <remarks/>
        public string companyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public string groupCode {
            get {
                return this.groupCodeField;
            }
            set {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public int groupType {
            get {
                return this.groupTypeField;
            }
            set {
                this.groupTypeField = value;
            }
        }
        
        /// <remarks/>
        public int level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public string memberAliasName {
            get {
                return this.memberAliasNameField;
            }
            set {
                this.memberAliasNameField = value;
            }
        }
        
        /// <remarks/>
        public int memberType {
            get {
                return this.memberTypeField;
            }
            set {
                this.memberTypeField = value;
            }
        }
        
        /// <remarks/>
        public int policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class UserGroupResponse {
        
        private int countField;
        
        private Response responseField;
        
        private UserGroupInfo[] userGroupInfoField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("userGroupInfo")]
        public UserGroupInfo[] userGroupInfo {
            get {
                return this.userGroupInfoField;
            }
            set {
                this.userGroupInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class QueryGroupMemberResponse {
        
        private int countField;
        
        private Response responseField;
        
        private GroupMemberInfo[] gMemInfoField;
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public Response response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gMemInfo")]
        public GroupMemberInfo[] gMemInfo {
            get {
                return this.gMemInfoField;
            }
            set {
                this.gMemInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class QedResponse {
        
        private QueryGroupMemberResponse qGMemResponseField;
        
        private UserGroupResponse uGroupResponseField;
        
        private CompanyGroupResponse companyGroupResponseField;
        
        private CompanyUserResponse companyUserResponseField;
        
        private CompanyResponse companyResponseField;
        
        private GroupMemberResponse groupMemResponseField;
        
        private GroupResponse groupResponseField;
        
        private AddGroupResponse addGroupResponseField;
        
        private DeleteGroupResponse deleteGroupResponseField;
        
        private GroupUpdateResponse groupUpdateResponseField;
        
        private UserResponse userResponseField;
        
        /// <remarks/>
        public QueryGroupMemberResponse QGMemResponse {
            get {
                return this.qGMemResponseField;
            }
            set {
                this.qGMemResponseField = value;
            }
        }
        
        /// <remarks/>
        public UserGroupResponse UGroupResponse {
            get {
                return this.uGroupResponseField;
            }
            set {
                this.uGroupResponseField = value;
            }
        }
        
        /// <remarks/>
        public CompanyGroupResponse companyGroupResponse {
            get {
                return this.companyGroupResponseField;
            }
            set {
                this.companyGroupResponseField = value;
            }
        }
        
        /// <remarks/>
        public CompanyUserResponse companyUserResponse {
            get {
                return this.companyUserResponseField;
            }
            set {
                this.companyUserResponseField = value;
            }
        }
        
        /// <remarks/>
        public CompanyResponse companyResponse {
            get {
                return this.companyResponseField;
            }
            set {
                this.companyResponseField = value;
            }
        }
        
        /// <remarks/>
        public GroupMemberResponse groupMemResponse {
            get {
                return this.groupMemResponseField;
            }
            set {
                this.groupMemResponseField = value;
            }
        }
        
        /// <remarks/>
        public GroupResponse groupResponse {
            get {
                return this.groupResponseField;
            }
            set {
                this.groupResponseField = value;
            }
        }
        
        /// <remarks/>
        public AddGroupResponse addGroupResponse {
            get {
                return this.addGroupResponseField;
            }
            set {
                this.addGroupResponseField = value;
            }
        }
        
        /// <remarks/>
        public DeleteGroupResponse deleteGroupResponse {
            get {
                return this.deleteGroupResponseField;
            }
            set {
                this.deleteGroupResponseField = value;
            }
        }
        
        /// <remarks/>
        public GroupUpdateResponse groupUpdateResponse {
            get {
                return this.groupUpdateResponseField;
            }
            set {
                this.groupUpdateResponseField = value;
            }
        }
        
        /// <remarks/>
        public UserResponse userResponse {
            get {
                return this.userResponseField;
            }
            set {
                this.userResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class UserRequest {
        
        private UserInfo userInfoField;
        
        /// <remarks/>
        public UserInfo userInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class QueryRequest {
        
        private string mainParamField;
        
        private int pageSizeField;
        
        private int startPosField;
        
        /// <remarks/>
        public string mainParam {
            get {
                return this.mainParamField;
            }
            set {
                this.mainParamField = value;
            }
        }
        
        /// <remarks/>
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public int startPos {
            get {
                return this.startPosField;
            }
            set {
                this.startPosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class GroupRequest {
        
        private GroupInfo groupInfoField;
        
        /// <remarks/>
        public GroupInfo groupInfo {
            get {
                return this.groupInfoField;
            }
            set {
                this.groupInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://qed.qchat.telecom.cn")]
    public partial class AddGroupRequest {
        
        private string adminAccountField;
        
        private GroupInfo groupInfoField;
        
        /// <remarks/>
        public string adminAccount {
            get {
                return this.adminAccountField;
            }
            set {
                this.adminAccountField = value;
            }
        }
        
        /// <remarks/>
        public GroupInfo groupInfo {
            get {
                return this.groupInfoField;
            }
            set {
                this.groupInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void queryCompanyCompletedEventHandler(object sender, queryCompanyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCompanyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryCompanyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void queryCompanyGroupCompletedEventHandler(object sender, queryCompanyGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCompanyGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryCompanyGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void queryCompanyUserCompletedEventHandler(object sender, queryCompanyUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCompanyUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryCompanyUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void queryGroupCompletedEventHandler(object sender, queryGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void addGroupCompletedEventHandler(object sender, addGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void deleteGroupCompletedEventHandler(object sender, deleteGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void updateGroupCompletedEventHandler(object sender, updateGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void queryGroupMemberCompletedEventHandler(object sender, queryGroupMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryGroupMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryGroupMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void addGroupMemberCompletedEventHandler(object sender, addGroupMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addGroupMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addGroupMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void updateGroupMemberCompletedEventHandler(object sender, updateGroupMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateGroupMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateGroupMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void deleteGroupMemberCompletedEventHandler(object sender, deleteGroupMemberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteGroupMemberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteGroupMemberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void queryUserCompletedEventHandler(object sender, queryUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void queryUserGroupCompletedEventHandler(object sender, queryUserGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryUserGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryUserGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void updateUserCompletedEventHandler(object sender, updateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void updateUserStatusCompletedEventHandler(object sender, updateUserStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateUserStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateUserStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QedResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QedResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591