//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1008 版自动生成。
// 
#pragma warning disable 1591

namespace WebUnicomAction.UnicomService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServicePtytSoap11Binding", Namespace="WebServicePtyt")]
    public partial class WebServicePtyt : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback QueryGroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback testOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAuthorityModifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryUserListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryGroupUserListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GroupUserDistributionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAuthorityQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryUserInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServicePtyt() {
            this.Url = global::WebUnicomAction.Properties.Settings.Default.WebUnicomAction_UnicomService_WebServicePtyt;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryGroupListCompletedEventHandler QueryGroupListCompleted;
        
        /// <remarks/>
        public event testCompletedEventHandler testCompleted;
        
        /// <remarks/>
        public event UserAuthorityModifyCompletedEventHandler UserAuthorityModifyCompleted;
        
        /// <remarks/>
        public event QueryUserListCompletedEventHandler QueryUserListCompleted;
        
        /// <remarks/>
        public event ModifyUserCompletedEventHandler ModifyUserCompleted;
        
        /// <remarks/>
        public event QueryGroupUserListCompletedEventHandler QueryGroupUserListCompleted;
        
        /// <remarks/>
        public event DeleteUserCompletedEventHandler DeleteUserCompleted;
        
        /// <remarks/>
        public event AddUserCompletedEventHandler AddUserCompleted;
        
        /// <remarks/>
        public event ModifyGroupCompletedEventHandler ModifyGroupCompleted;
        
        /// <remarks/>
        public event GroupUserDistributionCompletedEventHandler GroupUserDistributionCompleted;
        
        /// <remarks/>
        public event UserAuthorityQueryCompletedEventHandler UserAuthorityQueryCompleted;
        
        /// <remarks/>
        public event DeleteGroupCompletedEventHandler DeleteGroupCompleted;
        
        /// <remarks/>
        public event AddGroupCompletedEventHandler AddGroupCompleted;
        
        /// <remarks/>
        public event QueryUserInfoCompletedEventHandler QueryUserInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:QueryGroupList", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string QueryGroupList() {
            object[] results = this.Invoke("QueryGroupList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryGroupListAsync() {
            this.QueryGroupListAsync(null);
        }
        
        /// <remarks/>
        public void QueryGroupListAsync(object userState) {
            if ((this.QueryGroupListOperationCompleted == null)) {
                this.QueryGroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryGroupListOperationCompleted);
            }
            this.InvokeAsync("QueryGroupList", new object[0], this.QueryGroupListOperationCompleted, userState);
        }
        
        private void OnQueryGroupListOperationCompleted(object arg) {
            if ((this.QueryGroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryGroupListCompleted(this, new QueryGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:test", RequestNamespace="WebServicePtyt", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void test() {
            this.Invoke("test", new object[0]);
        }
        
        /// <remarks/>
        public void testAsync() {
            this.testAsync(null);
        }
        
        /// <remarks/>
        public void testAsync(object userState) {
            if ((this.testOperationCompleted == null)) {
                this.testOperationCompleted = new System.Threading.SendOrPostCallback(this.OntestOperationCompleted);
            }
            this.InvokeAsync("test", new object[0], this.testOperationCompleted, userState);
        }
        
        private void OntestOperationCompleted(object arg) {
            if ((this.testCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.testCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:UserAuthorityModify", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string UserAuthorityModify([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string authorityXml) {
            object[] results = this.Invoke("UserAuthorityModify", new object[] {
                        userNum,
                        authorityXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserAuthorityModifyAsync(string userNum, string authorityXml) {
            this.UserAuthorityModifyAsync(userNum, authorityXml, null);
        }
        
        /// <remarks/>
        public void UserAuthorityModifyAsync(string userNum, string authorityXml, object userState) {
            if ((this.UserAuthorityModifyOperationCompleted == null)) {
                this.UserAuthorityModifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAuthorityModifyOperationCompleted);
            }
            this.InvokeAsync("UserAuthorityModify", new object[] {
                        userNum,
                        authorityXml}, this.UserAuthorityModifyOperationCompleted, userState);
        }
        
        private void OnUserAuthorityModifyOperationCompleted(object arg) {
            if ((this.UserAuthorityModifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAuthorityModifyCompleted(this, new UserAuthorityModifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:QueryUserList", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string QueryUserList() {
            object[] results = this.Invoke("QueryUserList", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryUserListAsync() {
            this.QueryUserListAsync(null);
        }
        
        /// <remarks/>
        public void QueryUserListAsync(object userState) {
            if ((this.QueryUserListOperationCompleted == null)) {
                this.QueryUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryUserListOperationCompleted);
            }
            this.InvokeAsync("QueryUserList", new object[0], this.QueryUserListOperationCompleted, userState);
        }
        
        private void OnQueryUserListOperationCompleted(object arg) {
            if ((this.QueryUserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryUserListCompleted(this, new QueryUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ModifyUser", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string ModifyUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userXml) {
            object[] results = this.Invoke("ModifyUser", new object[] {
                        userNum,
                        userXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyUserAsync(string userNum, string userXml) {
            this.ModifyUserAsync(userNum, userXml, null);
        }
        
        /// <remarks/>
        public void ModifyUserAsync(string userNum, string userXml, object userState) {
            if ((this.ModifyUserOperationCompleted == null)) {
                this.ModifyUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyUserOperationCompleted);
            }
            this.InvokeAsync("ModifyUser", new object[] {
                        userNum,
                        userXml}, this.ModifyUserOperationCompleted, userState);
        }
        
        private void OnModifyUserOperationCompleted(object arg) {
            if ((this.ModifyUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyUserCompleted(this, new ModifyUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:QueryGroupUserList", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string QueryGroupUserList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string groupNum) {
            object[] results = this.Invoke("QueryGroupUserList", new object[] {
                        groupNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryGroupUserListAsync(string groupNum) {
            this.QueryGroupUserListAsync(groupNum, null);
        }
        
        /// <remarks/>
        public void QueryGroupUserListAsync(string groupNum, object userState) {
            if ((this.QueryGroupUserListOperationCompleted == null)) {
                this.QueryGroupUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryGroupUserListOperationCompleted);
            }
            this.InvokeAsync("QueryGroupUserList", new object[] {
                        groupNum}, this.QueryGroupUserListOperationCompleted, userState);
        }
        
        private void OnQueryGroupUserListOperationCompleted(object arg) {
            if ((this.QueryGroupUserListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryGroupUserListCompleted(this, new QueryGroupUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:DeleteUser", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string DeleteUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userNum) {
            object[] results = this.Invoke("DeleteUser", new object[] {
                        userNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserAsync(string userNum) {
            this.DeleteUserAsync(userNum, null);
        }
        
        /// <remarks/>
        public void DeleteUserAsync(string userNum, object userState) {
            if ((this.DeleteUserOperationCompleted == null)) {
                this.DeleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserOperationCompleted);
            }
            this.InvokeAsync("DeleteUser", new object[] {
                        userNum}, this.DeleteUserOperationCompleted, userState);
        }
        
        private void OnDeleteUserOperationCompleted(object arg) {
            if ((this.DeleteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserCompleted(this, new DeleteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:AddUser", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string AddUser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userXml) {
            object[] results = this.Invoke("AddUser", new object[] {
                        userNum,
                        userXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddUserAsync(string userNum, string userXml) {
            this.AddUserAsync(userNum, userXml, null);
        }
        
        /// <remarks/>
        public void AddUserAsync(string userNum, string userXml, object userState) {
            if ((this.AddUserOperationCompleted == null)) {
                this.AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserOperationCompleted);
            }
            this.InvokeAsync("AddUser", new object[] {
                        userNum,
                        userXml}, this.AddUserOperationCompleted, userState);
        }
        
        private void OnAddUserOperationCompleted(object arg) {
            if ((this.AddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserCompleted(this, new AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:ModifyGroup", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string ModifyGroup([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string groupNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string groupXml) {
            object[] results = this.Invoke("ModifyGroup", new object[] {
                        groupNum,
                        groupXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyGroupAsync(string groupNum, string groupXml) {
            this.ModifyGroupAsync(groupNum, groupXml, null);
        }
        
        /// <remarks/>
        public void ModifyGroupAsync(string groupNum, string groupXml, object userState) {
            if ((this.ModifyGroupOperationCompleted == null)) {
                this.ModifyGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyGroupOperationCompleted);
            }
            this.InvokeAsync("ModifyGroup", new object[] {
                        groupNum,
                        groupXml}, this.ModifyGroupOperationCompleted, userState);
        }
        
        private void OnModifyGroupOperationCompleted(object arg) {
            if ((this.ModifyGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyGroupCompleted(this, new ModifyGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GroupUserDistribution", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string GroupUserDistribution([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string groupNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userXml) {
            object[] results = this.Invoke("GroupUserDistribution", new object[] {
                        groupNum,
                        userXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GroupUserDistributionAsync(string groupNum, string userXml) {
            this.GroupUserDistributionAsync(groupNum, userXml, null);
        }
        
        /// <remarks/>
        public void GroupUserDistributionAsync(string groupNum, string userXml, object userState) {
            if ((this.GroupUserDistributionOperationCompleted == null)) {
                this.GroupUserDistributionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGroupUserDistributionOperationCompleted);
            }
            this.InvokeAsync("GroupUserDistribution", new object[] {
                        groupNum,
                        userXml}, this.GroupUserDistributionOperationCompleted, userState);
        }
        
        private void OnGroupUserDistributionOperationCompleted(object arg) {
            if ((this.GroupUserDistributionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GroupUserDistributionCompleted(this, new GroupUserDistributionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:UserAuthorityQuery", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string UserAuthorityQuery([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userNum) {
            object[] results = this.Invoke("UserAuthorityQuery", new object[] {
                        userNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UserAuthorityQueryAsync(string userNum) {
            this.UserAuthorityQueryAsync(userNum, null);
        }
        
        /// <remarks/>
        public void UserAuthorityQueryAsync(string userNum, object userState) {
            if ((this.UserAuthorityQueryOperationCompleted == null)) {
                this.UserAuthorityQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAuthorityQueryOperationCompleted);
            }
            this.InvokeAsync("UserAuthorityQuery", new object[] {
                        userNum}, this.UserAuthorityQueryOperationCompleted, userState);
        }
        
        private void OnUserAuthorityQueryOperationCompleted(object arg) {
            if ((this.UserAuthorityQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAuthorityQueryCompleted(this, new UserAuthorityQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:DeleteGroup", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string DeleteGroup([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string groupNum) {
            object[] results = this.Invoke("DeleteGroup", new object[] {
                        groupNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteGroupAsync(string groupNum) {
            this.DeleteGroupAsync(groupNum, null);
        }
        
        /// <remarks/>
        public void DeleteGroupAsync(string groupNum, object userState) {
            if ((this.DeleteGroupOperationCompleted == null)) {
                this.DeleteGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteGroupOperationCompleted);
            }
            this.InvokeAsync("DeleteGroup", new object[] {
                        groupNum}, this.DeleteGroupOperationCompleted, userState);
        }
        
        private void OnDeleteGroupOperationCompleted(object arg) {
            if ((this.DeleteGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteGroupCompleted(this, new DeleteGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:AddGroup", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string AddGroup([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string groupNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string groupXml) {
            object[] results = this.Invoke("AddGroup", new object[] {
                        groupNum,
                        groupXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddGroupAsync(string groupNum, string groupXml) {
            this.AddGroupAsync(groupNum, groupXml, null);
        }
        
        /// <remarks/>
        public void AddGroupAsync(string groupNum, string groupXml, object userState) {
            if ((this.AddGroupOperationCompleted == null)) {
                this.AddGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddGroupOperationCompleted);
            }
            this.InvokeAsync("AddGroup", new object[] {
                        groupNum,
                        groupXml}, this.AddGroupOperationCompleted, userState);
        }
        
        private void OnAddGroupOperationCompleted(object arg) {
            if ((this.AddGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddGroupCompleted(this, new AddGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:QueryUserInfo", RequestNamespace="WebServicePtyt", ResponseNamespace="WebServicePtyt", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string QueryUserInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userNum) {
            object[] results = this.Invoke("QueryUserInfo", new object[] {
                        userNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryUserInfoAsync(string userNum) {
            this.QueryUserInfoAsync(userNum, null);
        }
        
        /// <remarks/>
        public void QueryUserInfoAsync(string userNum, object userState) {
            if ((this.QueryUserInfoOperationCompleted == null)) {
                this.QueryUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryUserInfoOperationCompleted);
            }
            this.InvokeAsync("QueryUserInfo", new object[] {
                        userNum}, this.QueryUserInfoOperationCompleted, userState);
        }
        
        private void OnQueryUserInfoOperationCompleted(object arg) {
            if ((this.QueryUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryUserInfoCompleted(this, new QueryUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryGroupListCompletedEventHandler(object sender, QueryGroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryGroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryGroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void testCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserAuthorityModifyCompletedEventHandler(object sender, UserAuthorityModifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAuthorityModifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAuthorityModifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryUserListCompletedEventHandler(object sender, QueryUserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModifyUserCompletedEventHandler(object sender, ModifyUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryGroupUserListCompletedEventHandler(object sender, QueryGroupUserListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryGroupUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryGroupUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteUserCompletedEventHandler(object sender, DeleteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddUserCompletedEventHandler(object sender, AddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModifyGroupCompletedEventHandler(object sender, ModifyGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GroupUserDistributionCompletedEventHandler(object sender, GroupUserDistributionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupUserDistributionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GroupUserDistributionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserAuthorityQueryCompletedEventHandler(object sender, UserAuthorityQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAuthorityQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAuthorityQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteGroupCompletedEventHandler(object sender, DeleteGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddGroupCompletedEventHandler(object sender, AddGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryUserInfoCompletedEventHandler(object sender, QueryUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591